<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="mkrishnan" name="com.avlview.app.testcases.ProductListPageTest" tests="8" failures="1" timestamp="21 Dec 2018 07:56:28 GMT" time="178.002" errors="0">
  <testcase name="validateProductpageExistTest" time="21.142" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProductExistTest" time="22.057" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProductTemplateExistTest" time="21.504" classname="com.avlview.app.testcases.ProductListPageTest">
    <skipped/>
  </testcase> <!-- validateAddProductTemplateExistTest -->
  <testcase name="validateBackButtonTest" time="21.210" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateAddProduct" time="24.163" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateSearchExistTest" time="23.337" classname="com.avlview.app.testcases.ProductListPageTest"/>
  <testcase name="validateDeleteProduct" time="22.542" classname="com.avlview.app.testcases.ProductListPageTest">
    <failure type="java.lang.AssertionError" message="expected [You just deleted a product from records.] but found [Sorry, an error occurred. The servers are unable to complete your request at the moment. Please try again after a few minutes.]">
      <![CDATA[java.lang.AssertionError: expected [You just deleted a product from records.] but found [Sorry, an error occurred. The servers are unable to complete your request at the moment. Please try again after a few minutes.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.avlview.app.testcases.ProductListPageTest.validateDeleteProduct(ProductListPageTest.java:91)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateDeleteProduct -->
  <testcase name="validateDeleteProduct" time="22.047" classname="com.avlview.app.testcases.ProductListPageTest">
    <skipped/>
  </testcase> <!-- validateDeleteProduct -->
</testsuite> <!-- com.avlview.app.testcases.ProductListPageTest -->
