<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<a href=Sun_Jul_15_11_16_12_IST_2018.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jul_15_11_16_12_IST_2018.jpg target="_blank"><img src=Sun_Jul_15_11_16_12_IST_2018.jpg height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jul_15_11_16_13_IST_2018.jpg target="_blank">Screenshot link</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a href=Sun_Jul_15_11_16_13_IST_2018.jpg target="_blank"><img src=Sun_Jul_15_11_16_13_IST_2018.jpg height=200 width=200></a>]]>
    </line>
  </reporter-output>
  <suite name="TestNGLearning" duration-ms="2405" started-at="2018-07-15T05:46:11Z" finished-at="2018-07-15T05:46:14Z">
    <groups>
    </groups>
    <test name="Bank Manager Login Test" duration-ms="320" started-at="2018-07-15T05:46:11Z" finished-at="2018-07-15T05:46:12Z">
      <class name="testcases.BankManagerLoginTest">
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:testcases.BankManagerLoginTest@2b71e916]" name="loginAsBankManager" duration-ms="265" started-at="2018-07-15T05:46:11Z" finished-at="2018-07-15T05:46:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testcases.BankManagerLoginTest -->
    </test> <!-- Bank Manager Login Test -->
    <test name="Add Customer Test" duration-ms="1165" started-at="2018-07-15T05:46:12Z" finished-at="2018-07-15T05:46:13Z">
      <class name="testcases.AddCustomerTest">
        <test-method status="FAIL" signature="addCustomer(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.AddCustomerTest@6150c3ec]" name="addCustomer" duration-ms="663" started-at="2018-07-15T05:46:12Z" data-provider="getData" finished-at="2018-07-15T05:46:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Arora]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[A234234]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Customer added successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Add Customer Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Add Customer Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.AddCustomerTest.addCustomer(AddCustomerTest.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jul_15_11_16_12_IST_2018.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jul_15_11_16_12_IST_2018.jpg target="_blank"><img src=Sun_Jul_15_11_16_12_IST_2018.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- addCustomer -->
      </class> <!-- testcases.AddCustomerTest -->
    </test> <!-- Add Customer Test -->
    <test name="Open Account Test" duration-ms="883" started-at="2018-07-15T05:46:13Z" finished-at="2018-07-15T05:46:14Z">
      <class name="testcases.OpenAccountTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcases.OpenAccountTest@3fc2959f]" name="setUp" is-config="true" duration-ms="7019" started-at="2018-07-15T05:46:04Z" finished-at="2018-07-15T05:46:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="openAccount(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcases.OpenAccountTest@3fc2959f]" name="openAccount" duration-ms="505" started-at="2018-07-15T05:46:13Z" data-provider="getData" finished-at="2018-07-15T05:46:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman Arora]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Rupee]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Account created successfully]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Open Account Test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Open Account Test failed
at org.testng.Assert.fail(Assert.java:96)
at testcases.OpenAccountTest.openAccount(OpenAccountTest.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a href=Sun_Jul_15_11_16_13_IST_2018.jpg target="_blank">Screenshot link</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a href=Sun_Jul_15_11_16_13_IST_2018.jpg target="_blank"><img src=Sun_Jul_15_11_16_13_IST_2018.jpg height=200 width=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- openAccount -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcases.OpenAccountTest@3fc2959f]" name="tearDown" is-config="true" duration-ms="929" started-at="2018-07-15T05:46:14Z" finished-at="2018-07-15T05:46:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.OpenAccountTest -->
    </test> <!-- Open Account Test -->
  </suite> <!-- TestNGLearning -->
</testng-results>
